#################################################################################################
#                                                                                               #
#   This is the core configuration for a configuration service.  I have two examples here:      #
#                                                                                               #
#   -  A configuration service which completelty loads the configuration for the services       #
#     from the local file server of the config service.  This should only be used for           #
#     demonstration purposes or for a small application with a limited number of services.      #
#                                                                                               #
#   -  A configuraton service that uses a git-based repository to read the files from           #
#                                                                                               #
#################################################################################################


server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/santaniello/ms-in-action-config-repo/
          searchPaths: licensingservice,organizationservice
          #username: santaniello
          #password: f1012142
      label: master

######################################
# Classpath and file-based solution  #
######################################

#server:
#   port: 8888
#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#       # Because you’re using the filesystem for storing application configuration information,
#       # you need to tell Spring Cloud configuration server to run with the “native” profile.
#        native:
#          # To acess the default confs just use this url: http://localhost:8888/licensingservice/default
#          # To acess the dev confs just use this url:http://localhost:8888/licensingservice/dev
#          search-locations: file:////opt/idea-IU-181.4203.550/workspace/spring-microservices-in-action/configurationserver/src/main/resources/config/licensingservice

