server:
   port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
       # Because you’re using the filesystem for storing application configuration information,
       # you need to tell Spring Cloud configuration server to run with the “native” profile.
        native:
          search-locations: file:///Users/johncarnell1/book/spmia_code/chapter3-
                            code/confsvr/src/main/resources/config
